name: flutter_app_tp02

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.2.0
   

flutter:
  assets:
    - assets/logo.png
    - assets/products/laptop.png
    - assets/products/phone.png
    - assets/products/watch.png